-- ============================================================
-- Wedding Guest App — Seed Data
-- Run this AFTER schema.sql in Database → SQL Editor
-- Run only ONCE — re-running will update existing rows but not duplicate song requests
-- ============================================================

-- ─── Guest Info ───────────────────────────────────────────────────────────────
-- Pre-populate dietary, meal choices, and rehearsal dinner attendance.
-- The app only updates hotel/arrival/notes; these fields are preserved.

insert into public.guest_info (guest_name, dietary, meal_1, meal_2, meal_3, rehearsal_dinner) values
  ('Neha Pathmanaban',     '',                                                          'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Spinach & Ricotta Ravioli (Vegetarian)', true),
  ('Naveen Nath',          '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           true),
  ('Pathmanaban Raj',      '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Roasted Lamb',                           true),
  ('Kalpana Pathmanaban',  '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Roasted Lamb',                           true),
  ('Vishnu Pathmanaban',   'Allergic to all nuts and sesame',                           'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           true),
  ('Amar Nath',            '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           true),
  ('Sandhya Nath',         '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           true),
  ('Neel Nath',            '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           true),
  ('Aya Nath',             '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           true),
  ('Olivia Zhu',           '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           true),
  ('Akanksha Singh',       '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Spinach & Ricotta Ravioli (Vegetarian)', true),
  ('Suhail Goyal',         '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Spinach & Ricotta Ravioli (Vegetarian)', true),
  ('Sayantanee Das',       '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           true),
  ('Guhan Muruganandam',   '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Roasted Lamb',                           true),
  ('Ritika Patil',         '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', true),
  ('Kevin Labagnara',      '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Gaurie Mittal',        '',                                                          'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Roasted Lamb',                           true),
  ('Sai Avala',            '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Spinach & Ricotta Ravioli (Vegetarian)', true),
  ('Nikila Vasudevan',     'Allergic to shellfish',                                     'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', true),
  ('Goutham Subramanian',  '',                                                          'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Roasted Lamb',                           true),
  ('Liz Paulino',          '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', true),
  ('Andrew Ball',          '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Roasted Lamb',                           true),
  ('Connor Franklin',      '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Spinach & Ricotta Ravioli (Vegetarian)', true),
  ('Alec Mirchandani',     '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Spinach & Ricotta Ravioli (Vegetarian)', true),
  ('Eleni Karandreas',     '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Roasted Lamb',                           true),
  ('Alex Shih',            '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           true),
  ('Nancy Kwan',           '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           true),
  ('Jedidiah Glass',       '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Roasted Lamb',                           false),
  ('Edel Dhuibheanaigh',   '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Elliott Baker',        '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Mary Dick',            '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Andrew You',           '',                                                          'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Roasted Lamb',                           false),
  ('Jason Luo',            '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Grace Mutoko',         '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Roasted Lamb',                           false),
  ('Paul Mas',             '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Roasted Lamb',                           false),
  ('Sankash Shankar',      '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Bhavya Varma',         '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Leon Mirson',          '',                                                          'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Roasted Lamb',                           false),
  ('Moeko Nagatsuka',      '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Rushil Sheth',         'Shellfish allergy',                                         'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Tithi Raval',          '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Karam Tatla',          'Nut allergy; avocado allergy',                              'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Jenna Freedman',       '',                                                          'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Roasted Lamb',                           false),
  ('Ben Biswas',           'Peanut, almond and hazelnut allergy',                       'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Roasted Lamb',                           false),
  ('Danielle Skelly',      '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Subbarao Addaganti',   '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Anitha Addaganti',     'Allergy to mushrooms',                                      'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Yash Addaganti',       '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Trisha Addaganti',     'Allergy to eggs and mushrooms',                             'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Prasanna Bekal',       '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Roasted Lamb',                           false),
  ('Vindhya Bekal',        '',                                                          'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Pallavi Bekal',        '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Tanvi Bekal',          '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Roasted Lamb',                           false),
  ('Ram Sankaran',         '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Uma Ramanathan',       'Allergic to peanuts',                                       'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Rahul Ramanathan',     '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Abhay Mhatre',         '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Archana Mhatre',       '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Madhu Somenhalli',     '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Shashi Somenhalli',    '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Nithin Somenhalli',    '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Anand Palani',         '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Roasted Lamb',                           false),
  ('Sujatha Palani',       '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Arthi Palani',         '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Sainath Palani',       '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Vivek Seth',           '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Ashvani Vivek',        '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Saravanan Kandaswamy', '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Roasted Lamb',                           false),
  ('Chrisvin Jabamani',    'Allergic to shellfish',                                     'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Roasted Lamb',                           false),
  ('Howard Li',            '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Lingesh Radjou',       '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Rajesh Radjou',        '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Roasted Lamb',                           false),
  ('Prabakaran Vasan',     '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Kannagi Prabakaran',   '',                                                          'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Roasted Lamb',                           false),
  ('Neha Dubey',           '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Pooja Dubey',          'Vegetarian',                                                'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Rakesh Dubey',         '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Neelu Dubey',          '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Vijay Kumar',          '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Sadhana Kumar',        '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Vikas Kumar',          '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Riva Kumar',           '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Vivek Kumar',          '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Jaya Kumar',           '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Sanjay Mishra',        '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Seema Verma',          '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Shaan Mishra',         '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Maya Mishra',          'Vegetarian',                                                'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Anand Tewari',         '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Sangita Tewari',       '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Roasted Lamb',                           false),
  ('Jeevan Tewari',        '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Lauren Bordeaux',      '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Ravi Tewari',          '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Roasted Lamb',                           false),
  ('Tali Tudryn',          '',                                                          'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Roasted Lamb',                           false),
  ('Sanjiv Upadhyay',      '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Meena Upadhyay',       '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Archana Upadhyay',     '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Kirin Upadhyay',       '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Serena Upadhyay',      '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Roasted Lamb',                           false),
  ('Matt Uthupan',         '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Tushita Shrivastav',   '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Gugu Chohan',          '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Dennis Porto',         '',                                                          'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Jan Porto',            '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Diane Hedden',         '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Mary Kay Buchsbaum',   '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Bruce Buchsbaum',      '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Bruce Baker',          '',                                                          'Tuna Tataki',                    'Zucchini Risotto (Vegetarian)',   'Roasted Lamb',                           false),
  ('Kelli Baker',          '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Roshan Ram',           'Vegan; nut allergy (all nuts except peanuts and almonds)',  'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Bhavika Patel',        '',                                                          'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Jinesh Patel',         '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Radhika Kirpalani',    '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Tarun Kirpalani',      'No crab',                                                   'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Nitya Srikishen',      '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Puneet Lakhi',         'Gluten free and vegetarian',                                'Burrata & Watermelon (Vegetarian)', 'Zucchini Risotto (Vegetarian)', 'Spinach & Ricotta Ravioli (Vegetarian)', false),
  ('Marwan Bayoumy',       'No alcohol or pork',                                        'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Asokan Selvaraj',      '',                                                          'Tuna Tataki',                    'Roasted Prawn & Peach Tartare',   'Roasted Lamb',                           false),
  ('Sujatha Asokan',       '',                                                          'Burrata & Watermelon (Vegetarian)', 'Roasted Prawn & Peach Tartare', 'Roasted Lamb',                           false)
on conflict (guest_name) do update set
  dietary          = excluded.dietary,
  meal_1           = excluded.meal_1,
  meal_2           = excluded.meal_2,
  meal_3           = excluded.meal_3,
  rehearsal_dinner = excluded.rehearsal_dinner;


-- ─── Song Requests ────────────────────────────────────────────────────────────
-- Pre-populated from RSVP responses. Run only once.

insert into public.song_requests (song, artist, requested_by) values
  ('Appadi Podu! Pump It! Uppu Karuvadu!!', '',                          'Pathmanaban Raj'),
  ('Ni**as in Paris',                        'Jay-Z & Kanye West',       'Vishnu Pathmanaban'),
  ('Jalebi Baby',                            '',                          'Akanksha Singh'),
  ('Hotel Room Service',                     'Pitbull',                   'Sayantanee Das'),
  ('Low',                                    'Flo Rida',                  'Ritika Patil'),
  ('Rasputin',                               'Boney M',                   'Nikila Vasudevan'),
  ('Don''t Stop Me Now',                     'Queen',                     'Andrew Ball'),
  ('Breathe',                                'Tame Impala / Drake',       'Alec Mirchandani'),
  ('Can''t Stop the Feeling',                'Justin Timberlake',         'Jedidiah Glass'),
  ('Get Low',                                'Lil Jon & the Eastside Boyz', 'Elliott Baker'),
  ('Work from Home',                         'Fifth Harmony',             'Andrew You'),
  ('Sheila Ki Jawani',                       '',                          'Sankash Shankar'),
  ('Dancing Queen',                          'ABBA',                      'Bhavya Varma'),
  ('No Hands',                               'Waka Flocka Flame',         'Tithi Raval'),
  ('I Wanna Love You',                       'Akon',                      'Karam Tatla'),
  ('Mr. Brightside',                         'The Killers',               'Jenna Freedman'),
  ('Galla Goodiyaan / Kala Chashma',         '',                          'Subbarao Addaganti'),
  ('Gallan Goodiyaan / Starship / Sapphire', '',                          'Prasanna Bekal'),
  ('Tal Se Taal Mila',                       '',                          'Vijay Kumar'),
  ('The Thong Song',                         'Sisqó',                     'Vikas Kumar'),
  ('We Are Family',                          'Sister Sledge',             'Sanjay Mishra'),
  ('Rude Boy',                               'Rihanna',                   'Maya Mishra'),
  ('Anything by Ed Sheeran',                 'Ed Sheeran',                'Anand Tewari'),
  ('Anything by Nelly Furtado',              'Nelly Furtado',             'Jeevan Tewari'),
  ('Nueva Yol',                              'Bad Bunny',                 'Ravi Tewari'),
  ('Twist / Danza Kuduro',                   '',                          'Sanjiv Upadhyay'),
  ('Temperature',                            'Sean Paul',                 'Kirin Upadhyay'),
  ('I Love It',                              'Icona Pop',                 'Serena Upadhyay'),
  ('Ishq Tera Tadpaave',                     '',                          'Tushita Shrivastav'),
  ('Tupelo Honey',                           'Van Morrison',              'Dennis Porto'),
  ('Footloose',                              'Kenny Loggins',             'Diane Hedden'),
  ('Always',                                 'Atlantic Starr',            'Mary Kay Buchsbaum'),
  ('September',                              'Earth Wind & Fire',         'Bruce Baker'),
  ('Runaway',                                'Kanye West',                'Roshan Ram'),
  ('Tití Me Preguntó',                       'Bad Bunny',                 'Bhavika Patel'),
  ('Lamborghini / anything David Guetta',    'David Guetta',              'Radhika Kirpalani'),
  ('Ghoomar / Supda / Megha',                '',                          'Nitya Srikishen'),
  ('Baby',                                   'Justin Bieber',             'Pooja Dubey'),
  ('Valaiyapatti Thavile',                   '',                          'Anand Palani'),
  ('Badtameez Dil',                          '',                          'Saravanan Kandaswamy'),
  ('MIA',                                    'Drake & Bad Bunny',         'Chrisvin Jabamani'),
  ('Out of My League',                       'Fitz & the Tantrums',       'Howard Li');
