// ============================================================
// GUEST LIST
// ============================================================
// Guests type their name on the login screen to access the app.
// Matching is case-insensitive and ignores extra whitespace.

export const GUEST_LIST: string[] = [
  // --- Wedding Party ---
  "Neha Pathmanaban",
  "Naveen Nath",
  "Pathmanaban Raj",
  "Kalpana Pathmanaban",
  "Vishnu Pathmanaban",
  "Amar Nath",
  "Sandhya Nath",
  "Neel Nath",
  "Aya Nath",
  "Olivia Zhu",
  "Akanksha Singh",
  "Suhail Goyal",
  "Sayantanee Das",
  "Guhan Muruganandam",
  "Ritika Patil",
  "Kevin Labagnara",
  "Gaurie Mittal",
  "Sai Avala",
  "Nikila Vasudevan",
  "Goutham Subramanian",
  "Liz Paulino",
  "Andrew Ball",
  "Connor Franklin",
  "Alec Mirchandani",
  "Eleni Karandreas",
  "Alex Shih",
  "Nancy Kwan",

  // --- Guests ---
  "Jedidiah Glass",
  "Edel Dhuibheanaigh",
  "Elliott Baker",
  "Mary Dick",
  "Andrew You",
  "Jason Luo",
  "Grace Mutoko",
  "Paul Mas",
  "Sankash Shankar",
  "Bhavya Varma",
  "Leon Mirson",
  "Moeko Nagatsuka",
  "Rushil Sheth",
  "Tithi Raval",
  "Karam Tatla",
  "Jenna Freedman",
  "Ben Biswas",
  "Danielle Skelly",
  "Subbarao Addaganti",
  "Anitha Addaganti",
  "Yash Addaganti",
  "Trisha Addaganti",
  "Prasanna Bekal",
  "Vindhya Bekal",
  "Pallavi Bekal",
  "Tanvi Bekal",
  "Ram Sankaran",
  "Uma Ramanathan",
  "Rahul Ramanathan",
  "Abhay Mhatre",
  "Archana Mhatre",
  "Madhu Somenhalli",
  "Shashi Somenhalli",
  "Nithin Somenhalli",
  "Anand Palani",
  "Sujatha Palani",
  "Arthi Palani",
  "Sainath Palani",
  "Vivek Seth",
  "Ashvani Vivek",
  "Saravanan Kandaswamy",
  "Chrisvin Jabamani",
  "Howard Li",
  "Lingesh Radjou",
  "Rajesh Radjou",
  "Prabakaran Vasan",
  "Kannagi Prabakaran",
  "Neha Dubey",
  "Pooja Dubey",
  "Rakesh Dubey",
  "Neelu Dubey",
  "Vijay Kumar",
  "Sadhana Kumar",
  "Vikas Kumar",
  "Riva Kumar",
  "Vivek Kumar",
  "Jaya Kumar",
  "Sanjay Mishra",
  "Seema Verma",
  "Shaan Mishra",
  "Maya Mishra",
  "Anand Tewari",
  "Sangita Tewari",
  "Jeevan Tewari",
  "Lauren Bordeaux",
  "Ravi Tewari",
  "Tali Tudryn",
  "Sanjiv Upadhyay",
  "Meena Upadhyay",
  "Archana Upadhyay",
  "Kirin Upadhyay",
  "Serena Upadhyay",
  "Matt Uthupan",
  "Tushita Shrivastav",
  "Gugu Chohan",
  "Dennis Porto",
  "Jan Porto",
  "Diane Hedden",
  "Mary Kay Buchsbaum",
  "Bruce Buchsbaum",
  "Bruce Baker",
  "Kelli Baker",
  "Roshan Ram",
  "Bhavika Patel",
  "Jinesh Patel",
  "Radhika Kirpalani",
  "Tarun Kirpalani",
  "Nitya Srikishen",
  "Puneet Lakhi",
  "Marwan Bayoumy",
  "Asokan Selvaraj",
  "Sujatha Asokan",
  "Astrid Rolando",
];

// ============================================================
// GUEST GENDERS
// ============================================================
// Used by the Packing tab to show a tailored list (e.g. heels vs.
// dress shoes, saree pins vs. sherwani accessories). Guests not listed
// here fall back to seeing every item regardless of gender.

export type Gender = 'male' | 'female';

export const GUEST_GENDERS: Record<string, Gender> = {
  // --- Wedding Party ---
  "Neha Pathmanaban": 'female',
  "Naveen Nath": 'male',
  "Pathmanaban Raj": 'male',
  "Kalpana Pathmanaban": 'female',
  "Vishnu Pathmanaban": 'male',
  "Amar Nath": 'male',
  "Sandhya Nath": 'female',
  "Neel Nath": 'male',
  "Aya Nath": 'female',
  "Olivia Zhu": 'female',
  "Akanksha Singh": 'female',
  "Suhail Goyal": 'male',
  "Sayantanee Das": 'female',
  "Guhan Muruganandam": 'male',
  "Ritika Patil": 'female',
  "Kevin Labagnara": 'male',
  "Gaurie Mittal": 'female',
  "Sai Avala": 'male',
  "Nikila Vasudevan": 'female',
  "Goutham Subramanian": 'male',
  "Liz Paulino": 'female',
  "Andrew Ball": 'male',
  "Connor Franklin": 'male',
  "Alec Mirchandani": 'male',
  "Eleni Karandreas": 'female',
  "Alex Shih": 'male',
  "Nancy Kwan": 'female',

  // --- Guests ---
  "Jedidiah Glass": 'male',
  "Edel Dhuibheanaigh": 'female',
  "Elliott Baker": 'male',
  "Mary Dick": 'female',
  "Andrew You": 'male',
  "Jason Luo": 'male',
  "Grace Mutoko": 'female',
  "Paul Mas": 'male',
  "Sankash Shankar": 'male',
  "Bhavya Varma": 'female',
  "Leon Mirson": 'male',
  "Moeko Nagatsuka": 'female',
  "Rushil Sheth": 'male',
  "Tithi Raval": 'female',
  "Karam Tatla": 'male',
  "Jenna Freedman": 'female',
  "Ben Biswas": 'male',
  "Danielle Skelly": 'female',
  "Subbarao Addaganti": 'male',
  "Anitha Addaganti": 'female',
  "Yash Addaganti": 'male',
  "Trisha Addaganti": 'female',
  "Prasanna Bekal": 'male',
  "Vindhya Bekal": 'female',
  "Pallavi Bekal": 'female',
  "Tanvi Bekal": 'female',
  "Ram Sankaran": 'male',
  "Uma Ramanathan": 'female',
  "Rahul Ramanathan": 'male',
  "Abhay Mhatre": 'male',
  "Archana Mhatre": 'female',
  "Madhu Somenhalli": 'male',
  "Shashi Somenhalli": 'female',
  "Nithin Somenhalli": 'male',
  "Anand Palani": 'male',
  "Sujatha Palani": 'female',
  "Arthi Palani": 'female',
  "Sainath Palani": 'male',
  "Vivek Seth": 'male',
  "Ashvani Vivek": 'female',
  "Saravanan Kandaswamy": 'male',
  "Chrisvin Jabamani": 'male',
  "Howard Li": 'male',
  "Lingesh Radjou": 'male',
  "Rajesh Radjou": 'male',
  "Prabakaran Vasan": 'male',
  "Kannagi Prabakaran": 'female',
  "Neha Dubey": 'female',
  "Pooja Dubey": 'female',
  "Rakesh Dubey": 'male',
  "Neelu Dubey": 'female',
  "Vijay Kumar": 'male',
  "Sadhana Kumar": 'female',
  "Vikas Kumar": 'male',
  "Riva Kumar": 'female',
  "Vivek Kumar": 'male',
  "Jaya Kumar": 'female',
  "Sanjay Mishra": 'male',
  "Seema Verma": 'female',
  "Shaan Mishra": 'male',
  "Maya Mishra": 'female',
  "Anand Tewari": 'male',
  "Sangita Tewari": 'female',
  "Jeevan Tewari": 'male',
  "Lauren Bordeaux": 'female',
  "Ravi Tewari": 'male',
  "Tali Tudryn": 'female',
  "Sanjiv Upadhyay": 'male',
  "Meena Upadhyay": 'female',
  "Archana Upadhyay": 'female',
  "Kirin Upadhyay": 'female',
  "Serena Upadhyay": 'female',
  "Matt Uthupan": 'male',
  "Tushita Shrivastav": 'female',
  "Gugu Chohan": 'male',
  "Dennis Porto": 'male',
  "Jan Porto": 'female',
  "Diane Hedden": 'female',
  "Mary Kay Buchsbaum": 'female',
  "Bruce Buchsbaum": 'male',
  "Bruce Baker": 'male',
  "Kelli Baker": 'female',
  "Roshan Ram": 'male',
  "Bhavika Patel": 'female',
  "Jinesh Patel": 'male',
  "Radhika Kirpalani": 'female',
  "Tarun Kirpalani": 'male',
  "Nitya Srikishen": 'female',
  "Puneet Lakhi": 'male',
  "Marwan Bayoumy": 'male',
  "Asokan Selvaraj": 'male',
  "Sujatha Asokan": 'female',
  "Astrid Rolando": 'female',
};

// ============================================================
// WEDDING PARTY
// ============================================================
// Guests in this list see the Rehearsal Dinner on the schedule.

export const WEDDING_PARTY: string[] = [
  "Neha Pathmanaban",
  "Naveen Nath",
  "Pathmanaban Raj",
  "Kalpana Pathmanaban",
  "Vishnu Pathmanaban",
  "Amar Nath",
  "Sandhya Nath",
  "Neel Nath",
  "Aya Nath",
  "Olivia Zhu",
  "Akanksha Singh",
  "Suhail Goyal",
  "Sayantanee Das",
  "Guhan Muruganandam",
  "Ritika Patil",
  "Kevin Labagnara",
  "Gaurie Mittal",
  "Sai Avala",
  "Nikila Vasudevan",
  "Goutham Subramanian",
  "Liz Paulino",
  "Andrew Ball",
  "Connor Franklin",
  "Alec Mirchandani",
  "Eleni Karandreas",
  "Alex Shih",
  "Nancy Kwan",
];

// ============================================================
// HELPERS
// ============================================================

function normalizeName(name: string): string {
  return name.toLowerCase().trim().replace(/\s+/g, ' ');
}

export function isValidGuest(name: string): boolean {
  const normalized = normalizeName(name);
  return GUEST_LIST.some((guest) => normalizeName(guest) === normalized);
}

export function getCanonicalName(name: string): string | null {
  const normalized = normalizeName(name);
  return GUEST_LIST.find((guest) => normalizeName(guest) === normalized) ?? null;
}

export function isWeddingParty(name: string): boolean {
  const normalized = normalizeName(name);
  return WEDDING_PARTY.some((guest) => normalizeName(guest) === normalized);
}

export function getGuestGender(name: string): Gender | null {
  const normalized = normalizeName(name);
  for (const [guest, gender] of Object.entries(GUEST_GENDERS)) {
    if (normalizeName(guest) === normalized) return gender;
  }
  return null;
}
